### ISSUE TITLE
Error while installing (linked to p1_utils)

### ISSUE THREAD

**Issue by thbar** [processone/fast_xml#51]
Hello!

I'm having a look at `fast_xml` for a project.

I tried an installation initially via Livebook, then via a standalone `Mix.install/2` script:

```elixir
Mix.install([
  {:fast_xml, "~> 1.1"}
])
```

I get this error:

```
Resolving Hex dependencies...
Resolution completed in 0.029s
New:
  fast_xml 1.1.53
  p1_utils 1.0.26
* Getting fast_xml (Hex package)
* Getting p1_utils (Hex package)
===> Fetching pc v1.13.0
===> Analyzing applications...
===> Compiling pc
===> Compiling _build/default/plugins/pc/src/pc_port_env.erl failed
_build/default/plugins/pc/src/pc_port_env.erl:190:10: code:lib_dir/2 is deprecated; this functionality will be removed in a future release

===> Errors loading plugin pc. Run rebar3 with DEBUG=1 set to see errors.
===> Analyzing applications...
===> Compiling pc
===> Analyzing applications...
===> Compiling p1_utils
===> Compiling _build/default/plugins/pc/src/pc_port_env.erl failed
_build/default/plugins/pc/src/pc_port_env.erl:190:10: code:lib_dir/2 is deprecated; this functionality will be removed in a future release

** (Mix.Error) Could not compile dependency :p1_utils, "/Users/thbar/.asdf/installs/elixir/1.17.3-otp-27/.mix/elixir/1-17/rebar3 bare compile --paths /Users/thbar/Library/Caches/mix/installs/elixir-1.17.3-erts-15.1/45aaf55158b18999fc5884e8ed2c4f83/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You may run Mix.install/2 to try again or change the arguments to Mix.install/2 to try another version
    (mix 1.17.3) lib/mix.ex:588: Mix.raise/2
    (mix 1.17.3) lib/mix/tasks/deps.compile.ex:306: Mix.Tasks.Deps.Compile.do_command/5
    (mix 1.17.3) lib/mix/tasks/deps.compile.ex:211: Mix.Tasks.Deps.Compile.do_rebar3/2
    (mix 1.17.3) lib/mix/tasks/deps.compile.ex:93: anonymous fn/4 in Mix.Tasks.Deps.Compile.compile/2
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (mix 1.17.3) lib/mix/tasks/deps.compile.ex:77: Mix.Tasks.Deps.Compile.compile/2
    (mix 1.17.3) lib/mix/tasks/deps.loadpaths.ex:87: Mix.Tasks.Deps.Loadpaths.deps_check/2
    (mix 1.17.3) lib/mix/tasks/deps.loadpaths.ex:48: Mix.Tasks.Deps.Loadpaths.run/1
```

My setup (`.tool-versions` for asdf) is:

```
elixir 1.17.3-otp-27
erlang 27.1
```

And I'm running on a Mac M1 (Silicon arch).

**Comment by thbar** [comment]
Separating my own reply - this is solved by:
- https://github.com/processone/p1_utils/issues/16#issuecomment-1133895678

```
❯ mix local.rebar
/Users/thbar/.asdf/installs/elixir/1.17.3-otp-27/.mix/elixir/1-17/rebar3 already exists, overwrite? [Yn] Y
* creating /Users/thbar/.asdf/installs/elixir/1.17.3-otp-27/.mix/elixir/1-17/rebar3

playground/xml_explore on  xml-explore [$?] took 3s 
❯ elixir explore.exs
===> Analyzing applications...
===> Compiling p1_utils
===> Fetching pc v1.15.0
===> Analyzing applications...
===> Compiling pc
===> Compiling c_src/fxml.c
===> Compiling c_src/fxml_stream.c
===> Linking /Users/thbar/Library/Caches/mix/installs/elixir-1.17.3-erts-15.1/45aaf55158b18999fc5884e8ed2c4f83/_build/dev/lib/fast_xml/priv/lib/fxml.so
===> Linking /Users/thbar/Library/Caches/mix/installs/elixir-1.17.3-erts-15.1/45aaf55158b18999fc5884e8ed2c4f83/_build/dev/lib/fast_xml/priv/lib/fxml_stream.so
===> Analyzing applications...
===> Compiling fast_xml
```

**Comment by thbar** [comment]
I wonder if this is worth adding somewhere in the documentation here?
